apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: cdi.v1.3.0
  annotations:
    tectonic-visibility: ocs
spec:
  displayName: CDI
  description: |-
     A declarative Kubernetes utility to import Virtual Machine images for use with Kubevirt

  keywords: ['kubevirt', 'virtualization', 'virt', 'cdi']
  maturity: alpha
  version: 1.3.0
  maintainers:
  - name: RedHat
    email: lveyde@redhat.com
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: true
  provider:
    name: RedHat
  labels:
    operated-by: cdi
  selector:
    matchLabels:
      operated-by: cdi
  links:
  - name: Learn more about the KubeVirt project
    url: http://kubevirt.io/
  - name: Documentation
    url: https://github.com/kubevirt/containerized-data-importer/blob/master/README.md
  - name: CDI Source Code
    url: https://github.com/kubevirt/containerized-data-importer
  - name: CDI Operator Source Code
    url: https://github.com/kubevirt/cdi-operator

  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: cdi-operator
        rules:
        - apiGroups:
          - cdi.kubevirt.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
      deployments:
      - name: cdi-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: cdi-operator
          template:
            metadata:
              labels:
                app: cdi-operator
            spec:
              serviceAccountName: cdi-operator
              containers:
              - name: cdi-operator
                command:
                - ansible-operator
                image: docker.io/kubevirt/cdi-operator:v1.3.0
                ports:
                - containerPort: 60000
                  name: metrics
                imagePullPolicy: IfNotPresent
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAME
                  value: "cdi-operator"

  customresourcedefinitions:
    owned:
    - name: cdis.cdi.kubevirt.io
      version: v1alpha1
      kind: CDI
      displayName: CDI Application
      description: Represents an instance of a CDI application
